### ISSUE TITLE
存在的问题

### ISSUE THREAD

**Issue by SuperDannyBoy** [Li-Qun/iOS11_BigNavigationBarTitle#1]
使用此方法之后，下拉刷新控件会无法展示而被遮挡的情况。

**Comment by Li-Qun** [comment]
这个可以通过UI 布局解决
方法 （1）使用二级页面不可滚动 大标题
            并且 make.top.equalTo(@(self.dynamicNavView.bigTitleView.bottom));//【2】这块 的初始top位置要注意调整
          添加 mj_header
           效果和正常下拉刷新一样，缺点 大标题很大小屏幕 效果展示不佳
         （2）使用大导航可滚动
          并且 make.top.equalTo(@(self.dynamicNavView.bigTitleView.top));//【2】这块 的初始top位置要注意调整
         添加 mj_header
         效果下拉过程联动大导航看不到下拉状态，松手 可刷新
    
总结：如果是大导航栏还要加下拉刷新，以上方法可解决，已测试，可用。如不适用，尝试自己举一反三按需求定制符合产品要求的在大导航栏下面的下拉刷新（这个不是很友好在小屏幕上）
          祝一切顺利！如果有新方法欢迎告知分享
